name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Yarn install
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install

    - name: Run the tests
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: test

    - name: web-ext lint
      uses: kewisch/action-web-ext@v1.0
      with:
        # The web-ext command to run (lint, build, sign)
        cmd: lint
        # The source xpi or path
        source: ./src/browser-extension
        # More debugging fore certain steps
        verbose: true

    - name: "Upload Artifact"
      uses: actions/upload-artifact@master
      with:
        name: hyperapp-devtools-firefox-extension
        path: ./src/browser-extension
